- name: Set node information
  set_fact:
    _nodes: "{{ _nodes | default([]) + [{'hostname': item, 'address': hostvars[item].ansible_wlan0.ipv4.address}] }}"
    # _nodes: "{{ _nodes | default([]) + [{'hostname': hostvars[item].ansible_hostname, 'address': hostvars[item].ansible_wlan0.ipv4.address}] }}"
  run_once: yes
  with_items: "{{ ansible_play_hosts }}"
  when:
    - hostvars[item].ansible_wlan0 is defined

- name: Distribute hosts file
  become: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes